id: alien4cloud-kubernetes-plugin
name: kubernetes topology processing plugin
version: ${project.version}
description: >
  This plugin contains topology modifiers to transform a generic 
configuration_class: org.alien4cloud.plugin.kubernetes.PluginConfiguration
component_descriptors:
  - bean_name: kubernetes-modifier
    name: Kubernetes modifier.
    description: >
      Topology modifier (with namespace support) that transform a generic topology into a Kubernetes topology.
      Insert this modifier to post-location-match phase. Note that you MUST also insert the kubernetes-final-modifier to your location.
  - bean_name: kubernetes-final-modifier
    name: Kubernetes spec generator modifier.
    description: >
      This topology modifier generates kube yaml spec files and TOSCA nodes for deployment.
      Insert this modifier to post-matched-node-setup phase. Note that you MUST also insert the kubernetes-modifier to your location.
  - bean_name: kubernetes-adapter-modifier
    name: Kubernetes adapter modifier.
    description: >
      This topology modifier generates kube yaml spec files and TOSCA nodes for deployment from Kube ready concrete types.
      Use this modifier when you don't want to design portable topology but directly use kube compliant types.
      Insert this modifier to post-matched-node-setup phase.
      http://52.30.207.58:8800
  - bean_name: kubernetes-cleanuninstall-modifier
    name: Kubernetes clean uninstall modifier.
    description: >
      Remove all delete steps of uninstall workflow when a namespace resource is found (namespace deletion will remove all K8S resources).
